/** Database type definitions matching the Supabase schema. */

// ─── Together Mode ────────────────────────────────────────────────────────────
export type ConversationMode = 'invited' | 'together' | 'room' | 'meeting_mediation'

export type TogetherStage =
  | 'setup'
  | 'consent'
  | 'person_a_sharing'
  | 'person_a_summary_review'
  | 'person_b_sharing'
  | 'person_b_summary_review'
  | 'sharing_confirmation'
  | 'shared_understanding'
  | 'issue_discussion'
  | 'final_agreement'
  | 'completed'

export type TogetherSpeaker = 'person_a' | 'person_b'

export type IssueStatus = 'pending' | 'discussing' | 'agreed' | 'partial' | 'unresolved' | 'skipped'

export type OptionResponse = 'accept' | 'accept_with_changes' | 'reject' | 'need_info'

// AI-returned message review classification
export interface MessageReview {
  classification: 'display_as_written' | 'offer_reframe' | 'block_or_safety_intervention'
  originalMeaningSummary: string
  suggestedReframe?: string
  reason?: string
}

// Shared understanding generated by AI
export interface TogetherSharedUnderstanding {
  personASummary: string
  personBSummary: string
  agreements: Array<{ title: string; description: string }>
  differences: Array<{
    title: string
    personAPerspective: string
    personBPerspective: string
    neutralDescription: string
  }>
  issues: Array<{
    id: string
    title: string
    neutralDescription: string
    priority: number
  }>
}

// Final report for together sessions
export interface TogetherFinalReport {
  agreed: Array<{
    title: string
    personAAction: string
    personBAction: string
    sharedAction?: string
    dueDate?: string
    reviewDate?: string
  }>
  partiallyAgreed: Array<{
    title: string
    agreedParts: string
    unsettled: string
  }>
  notResolved: Array<{
    title: string
    personAPosition: string
    personBPosition: string
    suggestedNextStep: string
    revisitLater: boolean
  }>
  sharedUnderstanding: string
  safetyCategory: SafetyCategory
  safetyNote?: string
}

// DB row types
export interface DbTogetherSession {
  id: string
  case_id: string
  stage: TogetherStage
  current_speaker: TogetherSpeaker | null
  round_number: number
  person_a_name: string
  person_b_name: string
  topic: string
  consent_completed_at: string | null
  person_a_ready_confirmed_at: string | null
  person_b_ready_confirmed_at: string | null
  shared_understanding: TogetherSharedUnderstanding | null
  final_report: TogetherFinalReport | null
  completed_at: string | null
  paused_at: string | null
  created_at: string
  updated_at: string
}

export interface DbTogetherMessage {
  id: string
  session_id: string
  case_id: string
  speaker: TogetherSpeaker
  content: string
  voice_transcript: string | null
  message_review: MessageReview | null
  display_content: string | null
  reply_to_id: string | null
  round_number: number
  created_at: string
}

export interface DbTogetherTurnSummary {
  id: string
  session_id: string
  case_id: string
  speaker: TogetherSpeaker
  round_number: number
  ai_summary: string
  approved_summary: string | null
  approved_at: string | null
  created_at: string
}

export interface DbTogetherIssue {
  id: string
  session_id: string
  case_id: string
  title: string
  neutral_description: string
  priority: number
  status: IssueStatus
  resolution: string | null
  created_at: string
  updated_at: string
}

export interface DbTogetherIssueOption {
  id: string
  issue_id: string
  session_id: string
  proposed_by: TogetherSpeaker | 'urushi'
  description: string
  person_a_response: OptionResponse | null
  person_b_response: OptionResponse | null
  person_a_note: string | null
  person_b_note: string | null
  created_at: string
}

// ─── Room Mode (Live Mediation) ────────────────────────────────────────────────
export type RoomStage = 'setup' | 'consent' | 'ready' | 'live' | 'paused' | 'completed'

export type RoomInterventionAction =
  | 'LISTEN'
  | 'CLARIFY'
  | 'INVITE_PARTICIPANT'
  | 'REFRAME'
  | 'DEESCALATE'
  | 'IDENTIFY_ISSUE'
  | 'SUMMARIZE'
  | 'PROPOSE_COMPROMISE'
  | 'CONFIRM_AGREEMENT'
  | 'MOVE_TO_NEXT_ISSUE'
  | 'END_SESSION'

export type RoomTranscriptRole = 'participant' | 'assistant'

// Final report for room (Live Mediation) sessions
export interface RoomFinalReport {
  whatHappened: string
  agreed: Array<{ title: string; description: string }>
  unresolved: Array<{ title: string; description: string; suggestedNextStep: string }>
  participantActions: Array<{ participantName: string; actions: string[] }>
  nextSteps: string[]
  safetyCategory: SafetyCategory
  safetyNote?: string
}

export interface DbRoomSession {
  id: string
  case_id: string
  stage: RoomStage
  participant_count: 2 | 3
  topic: string
  context_summary: string | null
  source_case_id: string | null
  current_issue_id: string | null
  conversation_summary: string | null
  consent_completed_at: string | null
  realtime_session_active: boolean
  started_at: string | null
  ended_at: string | null
  paused_at: string | null
  final_report: RoomFinalReport | null
  created_at: string
  updated_at: string
}

export interface DbRoomParticipant {
  id: string
  session_id: string
  case_id: string
  participant_index: 1 | 2 | 3
  name: string
  pre_context: string | null
  speaker_label: string | null
  speaker_confidence: number | null
  calibrated_at: string | null
  created_at: string
}

export interface DbRoomIssue {
  id: string
  session_id: string
  case_id: string
  title: string
  neutral_description: string
  priority: number
  status: IssueStatus
  resolution: string | null
  created_at: string
  updated_at: string
}

export interface DbRoomAgreement {
  id: string
  session_id: string
  case_id: string
  issue_id: string | null
  description: string
  agreed_by: string[]
  awaiting: string[]
  confirmed: boolean
  confirmed_at: string | null
  proposed_at: string
  created_at: string
  updated_at: string
}

export interface DbRoomTranscriptSegment {
  id: string
  session_id: string
  case_id: string
  participant_id: string | null
  diarization_speaker_label: string | null
  speaker_confidence: number | null
  role: RoomTranscriptRole
  content: string
  sequence_number: number
  started_at: string | null
  ended_at: string | null
  created_at: string
}

export interface DbRoomIntervention {
  id: string
  session_id: string
  case_id: string
  action: RoomInterventionAction
  reasoning: string | null
  spoken_text: string | null
  triggered_at: string
  created_at: string
}

/** A non-browser client paired to a room session (e.g. a Raspberry Pi hardware client). */
export interface DbRoomDevice {
  id: string
  session_id: string
  case_id: string
  device_token_hash: string
  label: string | null
  paired_at: string
  last_seen_at: string | null
  revoked_at: string | null
  created_at: string
}

// ─── Meeting Mediation (Google Meet / Zoom, via a meeting-bot provider) ────────
export type MeetingPlatform = 'google_meet' | 'zoom'

export type MeetingBotProviderName = 'recall'

export type MeetingStatus =
  | 'setup'
  | 'awaiting_preparation'
  | 'ready'
  | 'bot_requested'
  | 'joining'
  | 'waiting_room'
  | 'in_meeting'
  | 'ended'
  | 'generating_report'
  | 'completed'
  | 'failed'
  | 'disconnected'
  | 'cancelled'

/** Same action set as Live Mediation's controller — one mediation engine, multiple transports. */
export type MeetingInterventionAction = RoomInterventionAction

export type MeetingTranscriptRole = RoomTranscriptRole

// Final report for meeting mediation sessions — same shape as Live Mediation's.
export type MeetingFinalReport = RoomFinalReport

export interface DbMeetingSession {
  id: string
  case_id: string
  status: MeetingStatus
  participant_count: 2 | 3
  topic: string
  context_summary: string | null
  meeting_platform: MeetingPlatform | null
  meeting_url: string | null
  scheduled_start_at: string | null
  timezone: string | null
  start_now: boolean
  bot_provider: MeetingBotProviderName
  provider_bot_id: string | null
  provider_meeting_id: string | null
  provider_metadata: Record<string, unknown> | null
  current_issue_id: string | null
  conversation_summary: string | null
  consent_completed_at: string | null
  requested_at: string | null
  joined_at: string | null
  ended_at: string | null
  failure_reason: string | null
  final_report: MeetingFinalReport | null
  created_at: string
  updated_at: string
}

export interface DbMeetingParticipant {
  id: string
  session_id: string
  case_id: string
  participant_index: 1 | 2 | 3
  name: string
  email: string | null
  is_initiator: boolean
  invite_token_hash: string | null
  invited_at: string | null
  encrypted_context: string | null
  context_iv: string | null
  context_tag: string | null
  context_submitted_at: string | null
  consented_at: string | null
  provider_participant_id: string | null
  created_at: string
}

export interface DbMeetingIssue {
  id: string
  session_id: string
  case_id: string
  title: string
  neutral_description: string
  priority: number
  status: IssueStatus
  resolution: string | null
  created_at: string
  updated_at: string
}

export interface DbMeetingAgreement {
  id: string
  session_id: string
  case_id: string
  issue_id: string | null
  description: string
  agreed_by: string[]
  awaiting: string[]
  confirmed: boolean
  confirmed_at: string | null
  proposed_at: string
  created_at: string
  updated_at: string
}

export interface DbMeetingTranscriptSegment {
  id: string
  session_id: string
  case_id: string
  participant_id: string | null
  provider_participant_id: string | null
  speaker_name: string | null
  role: MeetingTranscriptRole
  content: string
  sequence_number: number
  confidence: number | null
  started_at: string | null
  ended_at: string | null
  created_at: string
}

export interface DbMeetingIntervention {
  id: string
  session_id: string
  case_id: string
  action: MeetingInterventionAction
  reasoning: string | null
  spoken_text: string | null
  triggered_at: string
  created_at: string
}

export interface DbMeetingProviderEvent {
  id: string
  session_id: string | null
  bot_provider: MeetingBotProviderName
  provider_event_id: string
  event_type: string
  payload: Record<string, unknown> | null
  processed_at: string | null
  error_message: string | null
  created_at: string
}

export interface DbMeetingUsage {
  session_id: string
  meeting_duration_seconds: number | null
  transcript_segment_count: number
  intervention_count: number
  openai_input_tokens: number
  openai_output_tokens: number
  generated_audio_seconds: number
  provider_cost_usd: number | null
  estimated_total_cost_usd: number | null
  updated_at: string
}

export type CaseStatus =
  | 'draft'
  | 'awaiting_initiator'
  | 'awaiting_recipient'
  | 'ready_for_analysis'
  | 'analysing'
  | 'report_ready'
  | 'needs_safety_review'
  | 'declined'
  | 'closed'

export type ParticipantRole = 'initiator' | 'recipient'

export type MessageRole = 'participant' | 'assistant'

export type AnalysisStatus = 'pending' | 'running' | 'complete' | 'failed'

export type SafetyCategory =
  | 'ordinary_conflict'
  | 'high_conflict'
  | 'possible_coercion_or_abuse'
  | 'possible_self_harm_or_violence'
  | 'possible_child_safety_issue'
  | 'legal_or_professional_support_needed'

export type NotificationChannel = 'whatsapp' | 'email' | 'sms' | 'in_app'

export type NotificationStatus = 'queued' | 'sent' | 'delivered' | 'failed'

export type AgreementResponse = 'agreed' | 'needs_modification' | 'not_agreed'

export type RelationshipType =
  | 'partner_or_spouse'
  | 'family_member'
  | 'friend'
  | 'colleague'
  | 'business_partner'
  | 'manager_or_employee'
  | 'other'

export interface DbCase {
  id: string
  public_reference: string
  topic: string
  status: CaseStatus
  initiator_name: string
  recipient_name: string
  initiator_email: string | null
  initiator_phone: string | null
  recipient_email: string | null
  recipient_phone: string | null
  relationship: RelationshipType | null
  consent_version: string
  invitation_token_hash: string | null
  invite_expires_at: string | null
  created_at: string
  updated_at: string
  analysis_started_at: string | null
  analysis_completed_at: string | null
  closed_at: string | null
  invitation_brief?: string | null
  invitation_brief_approved_at?: string | null
  conversation_mode: ConversationMode
}

export interface InvitationBrief {
  title: string
  reasonForConversation: string
  issueFromPartyAPerspective: string
  hopedForOutcome: string
  invitationToRespond: string
}

export interface DbParticipant {
  id: string
  case_id: string
  role: ParticipantRole
  display_name: string
  email: string | null
  phone: string | null
  access_token_hash: string
  invitation_accepted_at: string | null
  consented_at: string | null
  intake_completed_at: string | null
  last_accessed_at: string | null
  created_at: string
}

export interface DbIntakeMessage {
  id: string
  case_id: string
  participant_id: string
  role: MessageRole
  encrypted_content: string
  encryption_iv: string
  encryption_tag: string
  sequence_number: number
  created_at: string
}

export interface DbSubmission {
  id: string
  case_id: string
  participant_id: string
  encrypted_summary: string
  encryption_iv: string
  encryption_tag: string
  submitted_at: string
  consented_for_shared_analysis: boolean
  revision_number: number
}

export interface DbAnalysis {
  id: string
  case_id: string
  status: AnalysisStatus
  model: string | null
  prompt_version: string | null
  structured_result: SharedReport | null
  safety_category: SafetyCategory | null
  safety_explanation: string | null
  error_message: string | null
  created_at: string
  updated_at: string
}

export interface DbAgreement {
  id: string
  case_id: string
  analysis_id: string
  agreement_text: string
  initiator_response: AgreementResponse | null
  recipient_response: AgreementResponse | null
  initiator_note: string | null
  recipient_note: string | null
  created_at: string
  updated_at: string
}

export interface DbNotificationLog {
  id: string
  case_id: string
  participant_id: string | null
  channel: NotificationChannel
  template_name: string
  provider_message_id: string | null
  status: NotificationStatus
  error_message: string | null
  sent_at: string | null
  created_at: string
}

export interface DbAuditEvent {
  id: string
  case_id: string | null
  participant_id: string | null
  event_type: string
  metadata: Record<string, unknown> | null
  ip_address: string | null
  created_at: string
}

// ─── Shared Report (stored in analyses.structured_result JSONB) ───────────────
export interface SharedReport {
  reportTitle: string
  bottomLine: string
  sharedGoals: string[]
  initiatorRecognition: PerspectiveRecognition
  recipientRecognition: PerspectiveRecognition
  behaviouralAssessments: BehaviouralAssessment[]
  disputedOrUnknownPoints: DisputedPoint[]
  escalationCycle: EscalationStep[]
  repairsRequired: Repair[]
  actionPlan: ActionStep[]
  suggestedWords: SuggestedWords[]
  workingAgreements: WorkingAgreement[]
  reviewPoint: ReviewPoint
  professionalSupportSuggestion: string | null
  safetyCategory: SafetyCategory
  safetyExplanation: string
  reportLimitations: string
}

export interface PerspectiveRecognition {
  validConcerns: string[]
  importantContext: string[]
  coreNeeds: string[]
  acknowledgementAlreadyOffered: string[]
}

export interface BehaviouralAssessment {
  owner: 'initiator' | 'recipient' | 'both'
  behaviour: string
  evidenceStatus: 'agreed' | 'acknowledged_by_actor' | 'reported_by_both' | 'reported_by_one' | 'disputed' | 'inference'
  assessment: 'not_acceptable' | 'needs_change' | 'reasonable' | 'cannot_determine'
  directFinding: string
  impact: string
  requiredChange: string | null
  requiredRepair: string | null
}

export interface DisputedPoint {
  issue: string
  initiatorView: string
  recipientView: string
  evidenceStatus: 'disputed'
  fairConclusion: string
}

export interface EscalationStep {
  step: number
  actor: 'initiator' | 'recipient' | 'both' | 'context'
  triggerOrInterpretation: string
  response: string
  impactOnCycle: string
}

export interface Repair {
  owner: 'initiator' | 'recipient' | 'both'
  owedTo: string
  reason: string
  acknowledgementNeeded: string
  actionNeeded: string
  mustNotRequire: string
  timeframe: string
}

export interface ActionStep {
  priority: number
  owner: 'initiator' | 'recipient' | 'both'
  action: string
  timeframe: string
  successMeasure: string
}

export interface SuggestedWords {
  speaker: 'initiator' | 'recipient'
  purpose: string
  script: string
}

export interface WorkingAgreement {
  agreement: string
  appliesTo: 'initiator' | 'recipient' | 'both'
  implementation: string
  breachResponse: string
}

export interface ReviewPoint {
  timeframe: string
  measuresOfProgress: string[]
  ifNoImprovement: string[]
}
